image: "node:12.7.0-alpine"

before_script:
  - apk update
  - apk add git
  - pwd
  - node -v
  - npm -v
  - yarn install

build:
  stage: build
  script:
    - yarn run build

lint:
  stage: test
  script:
    - yarn run lint

test:
  stage: test
  script:
    - yarn run pull-features
    - yarn run full-feature-test