image: "node:12.7.0-alpine"

.setup: &setup
  - apk update
  - apk add git
  - pwd
  - node -v
  - npm -v
  - yarn install

include:
  - template: Dependency-Scanning.gitlab-ci.yml

build:
  stage: build
  before_script:
    - *setup
  script:
    - yarn run build

lint:
  stage: test
  before_script:
    - *setup
  script:
    - yarn run lint

test:
  stage: test
  before_script:
    - *setup
  script:
    - yarn run pull-features
    - yarn run full-feature-test
